### ISSUE TITLE
Add forceWhite support for Hero web part

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/Slick-Sections#65]
## Test location:  /FPSSlickSections/SitePages/human-resource-career.aspx

![image](https://github.com/mikezimm/Slick-Sections/assets/49648086/89b6a1fb-8677-4f67-8013-99dc63537668)

**Comment by mikezimm** [comment]
Result:

![image](https://github.com/mikezimm/Slick-Sections/assets/49648086/877a5e86-e690-4a17-aa3e-bd0eba8157bd)

```css

/* For Hero Web Part  https://github.com/mikezimm/Slick-Sections/issues/65 */
.forceWhiteText [data-automation-id="Layers"] [data-automation-id="HeroTitle"] {
  transition:all 0.3s ease;
  color: white ;
}

/* Need !important for Hero Layer Patern HeroCallToAction */
.forceWhiteText [data-automation-id="Layers"] [data-automation-id="HeroCallToAction"] i,
.forceWhiteText [data-automation-id="Layers"] [data-automation-id="HeroCallToAction"],
.forceWhiteText [data-automation-id="Layers"] [data-automation-id="HeroPatternElement"] span {
  transition:all 0.3s ease;
  color: white !important;
}
```
